# Data Configuration
input_path: data/raw/
output_path: data/processed/

# Geospatial data settings
boundary_file: boundaries/BA_bairros_CD2022.shp
point_file: points/feira_de_santana_convertido.geojson

# Weather data settings
historical_path: weather/historical/
forecast_path: weather/forecast/

# Satellite data settings
dem_path: satellite/dem/
hand_path: satellite/hand/
