# Model Configuration
model_type: random_forest

# Training parameters
n_estimators: 100
max_depth: 10
random_state: 42

# Feature selection
features:
  - elevation
  - slope
  - hand
  - precipitation
  - temperature

# Validation
validation_split: 0.2
cross_validation: 5
